"""
This script evaluates a trained CWGAN generator for generating Room Impulse Responses (RIRs).
It provides two main functionalities:
1. Compute and save error metrics comparing generated and real RIRs to an Excel file.
2. Plot and save 100 randomly selected RIR comparisons.

Recommendation: For this evaluation script, it is advisable to use embeddings that have not been standardized.
"""

import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import os
from torch.utils.data import DataLoader
from model import Generator
from metrics import NMSEdBLoss, NPM, DRR, D50, RMSE
from rir_dataset import RIRDataset
from utils import load_data, align_rirs
import matplotlib.pyplot as plt
import argparse

# Set device to GPU if available, otherwise use CPU.
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def plot_rir(generated_rir, real_rir, index, extra, embedding, output_path):
    """
    Plot the generated and real RIRs, displaying their comparison and embedding details.
    generated_rir: The RIR generated by the model.
    real_rir: The actual RIR from the dataset.
    index: The index of the RIR being plotted.
    extra: A label for the plot (e.g., random or specific category).
    embedding: The embedding used for the generation.
    output_path: The directory to save the plot.
    """
    _, axs = plt.subplots(3, 1, figsize=(10, 8))
    axs[0].plot(generated_rir, label='Generated RIR')
    axs[0].plot(real_rir, label='True RIR')
    axs[0].legend()
    axs[0].set_title('Generated vs Real RIR')

    axs[1].plot(generated_rir, label='Generated RIR', color='tab:blue')
    axs[1].legend()
    axs[1].set_title("Generated RIR")

    axs[2].plot(generated_rir[0:300], label='Generated RIR')
    axs[2].plot(real_rir[0:300], label='True RIR')
    axs[2].legend()
    axs[2].set_title("First Samples")

    # Display the embedding details at the bottom of the figure
    embedding_text = "Embedding: " + ', '.join(f"{float(v):.2f}" for v in embedding.flatten())
    plt.figtext(0.5, 0.01, embedding_text, ha="center", fontsize=8, color="grey")

    # Save the plot to the specified directory
    plt.tight_layout()
    plt.savefig(os.path.join(output_path, f"rir_plot_{extra}_{index}.png"))
    plt.close()

def calculate_errors(generator, dataloader, z_dim, device):
    """
    Calculate various error metrics between generated and real RIRs.
    generator: The generator model.
    dataloader: DataLoader for the test data.
    z_dim: Dimensionality of the noise vector.
    device: Device to perform computations on (CPU/GPU).
    Returns lists of losses for each metric.
    """
    # Initialize loss criteria for different metrics
    criterion1 = nn.MSELoss()
    criterion2 = NMSEdBLoss()
    criterion4 = NPM()
    criterion5 = DRR()
    criterion6 = D50()
    rmse = RMSE()

    # Initialize lists to store the losses
    test_losses_mse, test_losses_nmse, test_losses_npm = [], [], []
    test_losses_drr, test_losses_D50, lags = [], [], []

    generator.eval()
    with torch.no_grad():
        for rirs, embeddings in dataloader:
            # Move data to the appropriate device
            rirs, embeddings = rirs.to(device), embeddings.to(device)
            z_noise = torch.randn(embeddings.size(0), z_dim).to(device)
            generated_rirs = generator(embeddings, z_noise)

            # Convert tensors to NumPy arrays for alignment
            rirs = rirs.squeeze().cpu().numpy()
            generated_rirs = generated_rirs.squeeze().cpu().numpy()

            # Align the real and generated RIRs
            adj_real_rir, adj_generated_rir, lag = align_rirs(rirs, generated_rirs)
            adj_real_rir = torch.from_numpy(adj_real_rir).to(device)
            adj_generated_rir = torch.from_numpy(adj_generated_rir).to(device)

            # Calculate various losses
            mse_loss = criterion1(adj_generated_rir, adj_real_rir).item()
            nmse_loss = criterion2(adj_generated_rir, adj_real_rir).item()
            npm_loss = criterion4(adj_generated_rir, adj_real_rir).item()

            # Calculate DRR and D50 losses
            n1 = 350  # Index for direct path cutoff
            drr_pred = criterion5(adj_generated_rir, nd=n1).item()
            drr_true = criterion5(adj_real_rir, nd=n1).item()
            loss_drr_diff = rmse(drr_true, drr_pred)
            D50_pred = criterion6(adj_generated_rir, ne=n1).item()
            D50_true = criterion6(adj_real_rir, ne=n1).item()
            loss_D50_diff = rmse(D50_true, D50_pred)

            # Append losses to their respective lists
            test_losses_mse.append(mse_loss)
            test_losses_nmse.append(nmse_loss)
            test_losses_npm.append(npm_loss)
            test_losses_drr.append(loss_drr_diff)
            test_losses_D50.append(loss_D50_diff)
            lags.append(lag)

    return test_losses_mse, test_losses_nmse, test_losses_npm, test_losses_drr, test_losses_D50

def save_errors_to_excel(rirs_filenames, distances, mse_losses, nmse_losses, npm_losses, drr_losses, D50_losses, output_path):
    """
    Save the calculated error metrics to an Excel file.
    rirs_filenames: List of RIR file names.
    distances: List of distances associated with the RIRs.
    mse_losses, nmse_losses, npm_losses, drr_losses, D50_losses: Lists of calculated losses.
    output_path: Directory where the Excel file will be saved.
    """
    # Calculate mean and variance for each metric
    mean_mse, variance_mse = np.mean(mse_losses), np.var(mse_losses)
    mean_nmse, variance_nmse = np.mean(nmse_losses), np.var(nmse_losses)
    mean_npm, variance_npm = np.mean(npm_losses), np.var(npm_losses)
    mean_drr, variance_drr = np.nanmean(drr_losses), np.nanvar(drr_losses)
    mean_D50, variance_D50 = np.mean(D50_losses), np.var(D50_losses)

    distances = [sublist for sublist in distances]
    rirs_filenames = [sublist for sublist in rirs_filenames]

    # Create a DataFrame to store the results
    data = {
        'RIR File': rirs_filenames + ['MEAN', 'VARIANCE'],
        'MSE Loss': mse_losses + [mean_mse, variance_mse],
        'NMSE Loss': nmse_losses + [mean_nmse, variance_nmse],
        'NormalizedProjectionMisalignment': npm_losses + [mean_npm, variance_npm],
        'DirectToReverberantRatio_diff': drr_losses + [mean_drr, variance_drr],
        'EarlyToTotalSoundEnergyRatio_diff': D50_losses + [mean_D50, variance_D50],
        'Distance': distances + ['', '']
    }

    # Save the results to an Excel file
    df = pd.DataFrame(data)
    excel_file_path = os.path.join(output_path, 'error_metrics.xlsx')
    df.to_excel(excel_file_path, index=False)
    print(f"Error metrics saved to: {excel_file_path}")

def indx_rir_generator(generator, rir_real, embedding, means, stds, z_dim, device):
    """
    Generate an RIR based on the given embedding and compare it to the real RIR.
    generator: The generator model.
    rir_real: The real RIR from the dataset.
    embedding: The embedding associated with the real RIR.
    means, stds: Mean and standard deviation of the embeddings for destandardization.
    z_dim: Dimensionality of the noise vector.
    device: Device to perform computations on (CPU/GPU).
    Returns aligned real and generated RIRs, along with the original embedding.
    """
    generator.eval()
    with torch.no_grad():
        # Convert embedding to tensor and generate RIR using the model
        embedding_tensor = torch.tensor(embedding, dtype=torch.float32).unsqueeze(0).to(device)
        z_noise = torch.randn(1, z_dim, dtype=torch.float32).to(device)
        rir_generated = generator(embedding_tensor, z_noise).squeeze().cpu().numpy()
        # Destandardize the embedding if necessary
        original_embedding = embedding.destandardize_data(embedding_tensor.cpu().numpy(), means, stds)

    # Align the real and generated RIRs for comparison
    rir_real_aligned, rir_generated_aligned, _ = align_rirs(rir_real, rir_generated)
    return rir_real_aligned, rir_generated_aligned, original_embedding

if __name__ == "__main__":
    # Argument parser for command-line inputs
    parser = argparse.ArgumentParser(description="Evaluate the CWGAN generator and perform analysis on test data.")
    parser.add_argument('--model_path', type=str, required=True, help="Path to the generator model file.")
    parser.add_argument('--output_path', type=str, required=True, help="Directory to save outputs (plots and/or Excel).")
    parser.add_argument('--cache_rir', type=str, required=True, help="Path to the cached RIR pickle file.")
    parser.add_argument('--cache_emb', type=str, required=True, help="Path to the cached embeddings pickle file.")
    parser.add_argument('--generate_excel', action='store_true', help="Generate and save error metrics to an Excel file.")
    parser.add_argument('--plot_rirs', action='store_true', help="Plot and save 100 randomly selected RIR comparisons.")
    args = parser.parse_args()

    z_dim = 50  # Dimension of the noise vector used for generation
    batch_size = 1  # Batch size for DataLoader

    # Load the generator model and its pre-trained weights
    generator = Generator(z_dim)
    generator.load_state_dict(torch.load(args.model_path, map_location=torch.device("cuda" if torch.cuda.is_available() else "cpu")))
    generator.to(torch.device("cuda" if torch.cuda.is_available() else "cpu"))

    # Load test data and embeddings
    emb_train, emb_test, rirs_train, rirs_test, distance_train, distance_test, file_names_train, file_names_test, feature_means, feature_stds = load_data(
        args.cache_rir, args.cache_emb, standardize=True)

    # Create DataLoader for the test set
    test_dataset = RIRDataset(rirs=rirs_test, embeddings=emb_test)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=4)

    if args.generate_excel:
        # Calculate errors using various metrics
        mse_losses, nmse_losses, npm_losses, drr_losses, D50_losses = calculate_errors(generator, test_loader, z_dim, torch.device("cuda" if torch.cuda.is_available() else "cpu"))
        # Save the calculated errors to an Excel file
        save_errors_to_excel(file_names_test, distance_test, mse_losses, nmse_losses, npm_losses, drr_losses, D50_losses, args.output_path)

    if args.plot_rirs:
        # Plot 100 randomly selected RIRs from the test set
        random_indices = np.random.choice(len(rirs_test), 100, replace=False)
        for idx in random_indices:
            rir_real_aligned, rir_generated_aligned, original_embedding = indx_rir_generator(
                generator, rirs_test[idx], emb_test[idx], feature_means, feature_stds, z_dim, torch.device("cuda" if torch.cuda.is_available() else "cpu"))
            # Save the RIR comparison plot
            plot_rir(rir_generated_aligned, rir_real_aligned, idx, 'random', original_embedding, args.output_path)
