"""
This script generates and visualizes Room Impulse Responses (RIRs) produced by a trained CWGAN generator.
It plots comparisons between real and generated RIRs and includes the corresponding embedding used.
"""
import torch
import numpy as np
import os
import argparse
import matplotlib.pyplot as plt
from models.cwgan_model import Generator
from ..misc.load_data import load_data
from ..trainers.cwgan_train import model_test

# Dimensiones de los arrays
def plot_rir(generated_rir: np.ndarray, real_rir: np.ndarray, embedding: np.ndarray, output_path: str = None) -> None:
    """
    Plot and optionally save the visual comparison between a generated and a real Room Impulse Response (RIR),
    including a zoomed-in view and the embedding used.

    Args:
        generated_rir (np.ndarray): 1D array of shape (L,) representing the generated RIR, where:

            - **L**: Number of audio samples.

        real_rir (np.ndarray): 1D array of shape (L,) representing the real RIR.

        embedding (np.ndarray): 1D array of shape (F,) containing the embedding vector, where:

            - **F**: Embedding dimensionality (typically 10).

        output_path (str, optional): Path to save the plot image. If None, the plot is not saved.
    """
    # Create a figure with three subplots for visualizing the RIRs
    _, axs = plt.subplots(3, 1, figsize=(10, 8))
    axs[0].plot(generated_rir, label='Generated RIR')
    axs[0].plot(real_rir, label='True RIR')
    axs[0].legend()
    axs[0].set_title('Generated vs Real RIR')

    axs[1].plot(generated_rir, label='Generated RIR', color='tab:blue')
    axs[1].legend()
    axs[1].set_title("Generated RIR")

    axs[2].plot(generated_rir[0:300], label='Generated RIR')
    axs[2].plot(real_rir[0:300], label='True RIR')
    axs[2].legend()
    axs[2].set_title("First Samples")

    # Add the embedding information as text below the plots
    embedding_text = "Embedding: " + ', '.join(f"{float(v):.2f}" for v in embedding.flatten())
    plt.figtext(0.5, 0.01, embedding_text, ha="center", fontsize=8, color="grey")

    plt.tight_layout()
    # Save the plot to the specified output directory
    if output_path is not None:
        plt.savefig(output_path)
    plt.close()

if __name__ == "__main__":
    # Parse command-line arguments for the visualization script
    parser = argparse.ArgumentParser(description="Visualize RIRs generated by a trained CWGAN generator.")
    parser.add_argument('--model_path', type=str, required=True, help="Path to the trained generator model.")
    parser.add_argument('--output_path', type=str, required=True, help="Directory to save the plots.")
    parser.add_argument('--cache_rir', type=str, required=True, help="Path to cached RIR data.")
    parser.add_argument('--cache_emb', type=str, required=True, help="Path to cached embeddings.")
    parser.add_argument('--z_dim', type=int, default=50, help="Dimensionality of the noise vector.")
    parser.add_argument('--n_plots', type=int, default=100, help="Number of RIRs to plot.")
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    generator = Generator(z_dim=args.z_dim)
    generator.load_state_dict(torch.load(args.model_path, map_location=device))
    generator.to(device)

    # Load the test data, embeddings, and normalization statistics
    emb_train, emb_test, rirs_train, rirs_test, distance_train, distance_test, file_names_train, file_names_test, feature_means, feature_stds = load_data(
        args.cache_rir, args.cache_emb)

    os.makedirs(args.output_path, exist_ok=True)

    # Generate and plot RIRs for a random subset of the test data
    random_indices = np.random.choice(len(rirs_test), args.n_plots, replace=False)
    for idx in random_indices:
        rir_real_aligned, rir_generated_aligned, original_embedding = model_test(
            generator, rirs_test[idx], emb_test[idx], feature_means, feature_stds, args.z_dim, device)
        # Plot and save the comparison between the real and generated RIRs
        plot_rir(rir_generated_aligned, rir_real_aligned, idx, original_embedding, args.output_path)
